import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import SideBar from './_components/sidebar'
import '../globals.css'

const inter = Inter({
  subsets: ['latin'],
  display: 'auto',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-Br">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-full gap-8">
          <SideBar />
          <div className="h-full w-full p-4">{children}</div>
        </div>
      </body>
    </html>
  )
}
